---
version: "{build}-{branch}"

image: Ubuntu2204

branches:
  only:
    - master
    - development

environment:
  fast_finish: true
  APPVEYOR_YML_DISABLE_PS_LINUX: true

platform:
  - x64

configuration:
  - release

install:
  - echo "--- Installing dependencies ---"
  - sudo apt-get --assume-yes update
  - sudo apt-get --assume-yes install cmake libglfw3-dev
  - sudo apt-get --assume-yes install liblcms2-dev libexif-dev libgif-dev libtiff5-dev libjpeg-turbo-dev libwebp-dev libilmbase-dev libopenexr-dev libopenjp2-7-dev libimlib2-dev
# - sudo apt-get --assume-yes install libjpeg-dev libpng-dev zlib1g-dev libxrandr-dev libxcursor-dev

build: off

build_script:
  - echo --- Building ---
  - make -j release
  - echo --- done ---

test: off
