# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.1

install:
  - echo "deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/fillwave_ext.list
  - echo "deb-src http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/fillwave_ext.list
  - sudo apt-get -qq -y update
  - sudo apt-get install cmake
  - sudo apt-get install libfreetype6-dev
  - sudo apt-get install libglfw3-dev
  - sudo apt-get install libimlib2-dev
  - sudo apt-get install libtiff5-dev
  - sudo apt-get install libjpeg-dev
  - sudo apt-get install libgif-dev
  - sudo apt-get install libpng12-dev
  - sudo apt-get install liblcms2-dev
  - sudo apt-get install libwebp-dev

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - make clean
          - make release