# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: gcc:6.1
image: atlassian/default-image:3

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # - echo "deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/fillwave_ext.list
          # - echo "deb-src http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/fillwave_ext.list
          - apt-get update -qq
          - apt-get install -y cmake libglfw3-dev libxrandr-dev libxcursor-dev libfreetype6-dev liblcms2-dev libexif-dev libimlib2-dev libtiff5-dev libjpeg-dev libgif-dev libpng-dev libwebp-dev
          - make clean
          - make release
